# Generated by Django 6.0.5 on 2026-09-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_stockreconciliation_cancelled_at_and_more'),
        ('menu', '0007_menuitem_menu_item_rate_gte_zero'),
        ('orders', '0029_backfill_order_created_by'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('department__in', ('FOOD', 'DRINKS'))), name='orders_item_department_valid'),
        ),
    ]
