# Generated by Django 6.0.5 on 2026-09-22 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_remove_journalentry_write_off_amount_and_more'),
        ('settings', '0036_restaurant_require_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionunit',
            name='sales_returns_account',
            field=models.ForeignKey(blank=True, help_text='The account debited when a sale from this station is refunded.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Sales returns account'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='default_sales_returns_account',
            field=models.ForeignKey(blank=True, help_text='The account used to reduce income on refunds when no kitchen/bar account is set.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Default sales returns account'),
        ),
    ]
