# Generated by Django 6.0.5 on 2026-09-22 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0037_productionunit_sales_returns_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='default_stock_in_hand_account',
        ),
    ]
