# Generated by Django 6.0.5 on 2026-09-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_dailypnlconsumptionrow_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypnl',
            name='food_usage_counted',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
